services:

  build:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    volumes:
      - .:/app
    environment:
      - APP_ENV=${APP_ENV:-prod}

  pocketbase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase_data:/app/pb_data
      - ./db/pb_public:/app/pb_public
      - ./db/pb_hooks:/app/pb_hooks
      - ./db/pb_migrations:/app/pb_migrations
    env_file:
      - .env
    networks:
      - amigo-secreto-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - NGINX_ENVSUBST_FILTER=APP_ENV
    volumes:
      - ./apps/web/dist/frontend/browser:/usr/share/nginx/html:ro
      - ./server/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./server/logs:/var/log/nginx
    depends_on:
      pocketbase:
        condition: service_healthy
      build:
        condition: ${DOCKER_BUILD_CONDITION:-service_completed_successfully}
    networks:
      - amigo-secreto-network

networks:
  amigo-secreto-network:
    driver: bridge
volumes:
  pocketbase_data:
