services:

  build:
    image: node:lts-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev:web:build"
    #command: sh -c "npm install && npm run dev:webwatch"    # switch to dev mode

  pocketbase:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase_data:/app/pb_data
      - ./db/pb_public:/app/pb_public
      - ./db/pb_hooks:/app/pb_hooks
      - ./db/pb_migrations:/app/pb_migrations
    env_file:
      - .env
    networks:
      - amigo-secreto-network
    depends_on:
      build:
        condition: service_completed_successfully # comment to dev mode

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./apps/web/dist/frontend/browser:/usr/share/nginx/html:ro
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/logs:/var/log/nginx
    depends_on:
      - pocketbase
    networks:
      - amigo-secreto-network

networks:
  amigo-secreto-network:
    driver: bridge
volumes:
  pocketbase_data:
